CREATE TABLE IF NOT EXISTS `img_search_instance` (
  `id` BIGINT NOT NULL,
  `provider` VARCHAR(32) NOT NULL,
  `region_id` VARCHAR(64) NOT NULL,
  `endpoint` VARCHAR(128) NOT NULL,
  `instance_name` VARCHAR(64) NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  `add_qps` INT NOT NULL DEFAULT 5,
  `search_qps` INT NOT NULL DEFAULT 5,
  `delete_qps` INT NOT NULL DEFAULT 20,
  `remark` VARCHAR(255) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider_region_instance` (`provider`, `region_id`, `instance_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `img_search_image` (
  `id` BIGINT NOT NULL,
  `instance_id` BIGINT NOT NULL,
  `biz_type` VARCHAR(32) NOT NULL,
  `sku` VARCHAR(64) NOT NULL,
  `spu` VARCHAR(64) DEFAULT NULL,
  `image_id` BIGINT NOT NULL,
  `product_id` VARCHAR(128) NOT NULL,
  `pic_name` VARCHAR(128) NOT NULL,
  `image_url` VARCHAR(1024) NOT NULL,
  `oss_bucket` VARCHAR(128) DEFAULT NULL,
  `oss_object_key` VARCHAR(512) DEFAULT NULL,
  `image_md5` CHAR(32) DEFAULT NULL,
  `mime_type` VARCHAR(128) DEFAULT NULL,
  `file_ext` VARCHAR(16) DEFAULT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `width` INT DEFAULT NULL,
  `height` INT DEFAULT NULL,
  `main_flag` TINYINT NOT NULL DEFAULT 0,
  `platform_id` BIGINT DEFAULT NULL,
  `site_id` BIGINT DEFAULT NULL,
  `category_id` BIGINT DEFAULT NULL,
  `category_path` VARCHAR(255) DEFAULT NULL,
  `indexable_flag` TINYINT NOT NULL DEFAULT 1,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `sync_status` TINYINT NOT NULL DEFAULT 0,
  `last_task_type` TINYINT DEFAULT NULL,
  `version` INT NOT NULL DEFAULT 1,
  `bucket_no` INT NOT NULL DEFAULT 0,
  `last_sync_time` DATETIME DEFAULT NULL,
  `last_request_id` VARCHAR(64) DEFAULT NULL,
  `last_error_code` VARCHAR(64) DEFAULT NULL,
  `last_error_msg` VARCHAR(512) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_image` (`instance_id`, `image_id`),
  UNIQUE KEY `uk_instance_product_pic` (`instance_id`, `product_id`, `pic_name`),
  KEY `idx_sku` (`sku`),
  KEY `idx_sync_status` (`sync_status`),
  KEY `idx_deleted_indexable` (`deleted`, `indexable_flag`),
  KEY `idx_bucket_id` (`bucket_no`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `img_search_sync_task` (
  `id` BIGINT NOT NULL,
  `task_no` VARCHAR(64) NOT NULL,
  `instance_id` BIGINT NOT NULL,
  `task_type` TINYINT NOT NULL,
  `biz_type` VARCHAR(32) NOT NULL,
  `image_pk_id` BIGINT NOT NULL,
  `image_id` BIGINT NOT NULL,
  `sku` VARCHAR(64) NOT NULL,
  `product_id` VARCHAR(128) NOT NULL,
  `pic_name` VARCHAR(128) NOT NULL,
  `target_version` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `retry_count` INT NOT NULL DEFAULT 0,
  `max_retry_count` INT NOT NULL DEFAULT 5,
  `next_retry_time` DATETIME DEFAULT NULL,
  `trace_id` VARCHAR(64) DEFAULT NULL,
  `request_id` VARCHAR(64) DEFAULT NULL,
  `error_code` VARCHAR(64) DEFAULT NULL,
  `error_msg` VARCHAR(512) DEFAULT NULL,
  `payload_json` JSON DEFAULT NULL,
  `start_time` DATETIME DEFAULT NULL,
  `finish_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_status_retry_time` (`status`, `next_retry_time`, `id`),
  KEY `idx_image_version` (`image_pk_id`, `target_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `img_search_rebuild_job` (
  `id` BIGINT NOT NULL,
  `job_no` VARCHAR(64) NOT NULL,
  `instance_id` BIGINT NOT NULL,
  `job_type` TINYINT NOT NULL,
  `scope_desc` VARCHAR(512) DEFAULT NULL,
  `snapshot_max_id` BIGINT DEFAULT NULL,
  `total_count` BIGINT NOT NULL DEFAULT 0,
  `success_count` BIGINT NOT NULL DEFAULT 0,
  `fail_count` BIGINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 0,
  `remark` VARCHAR(512) DEFAULT NULL,
  `start_time` DATETIME DEFAULT NULL,
  `finish_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_no` (`job_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `img_search_query_log` (
  `id` BIGINT NOT NULL,
  `query_no` VARCHAR(64) NOT NULL,
  `instance_id` BIGINT NOT NULL,
  `biz_scene` VARCHAR(32) NOT NULL,
  `query_source` TINYINT NOT NULL,
  `query_image_md5` CHAR(32) DEFAULT NULL,
  `query_image_url` VARCHAR(1024) DEFAULT NULL,
  `threshold_score` DECIMAL(5,4) DEFAULT NULL,
  `top_k` INT NOT NULL DEFAULT 20,
  `filter_expr` VARCHAR(1024) DEFAULT NULL,
  `docs_found` INT DEFAULT NULL,
  `docs_return` INT DEFAULT NULL,
  `search_time_ms` INT DEFAULT NULL,
  `top1_product_id` VARCHAR(128) DEFAULT NULL,
  `top1_pic_name` VARCHAR(128) DEFAULT NULL,
  `top1_score` DECIMAL(5,4) DEFAULT NULL,
  `request_id` VARCHAR(64) DEFAULT NULL,
  `operator_id` BIGINT DEFAULT NULL,
  `operator_name` VARCHAR(64) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_no` (`query_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `img_search_query_result` (
  `id` BIGINT NOT NULL,
  `query_log_id` BIGINT NOT NULL,
  `rank_no` INT NOT NULL,
  `product_id` VARCHAR(128) NOT NULL,
  `pic_name` VARCHAR(128) NOT NULL,
  `sku` VARCHAR(64) DEFAULT NULL,
  `image_id` BIGINT DEFAULT NULL,
  `score` DECIMAL(5,4) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
