-- 图搜实例配置表：保存阿里云图搜实例及限流配置
CREATE TABLE IF NOT EXISTS `img_search_instance` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `provider` VARCHAR(32) NOT NULL COMMENT '服务商标识，例如 ALIYUN',
  `region_id` VARCHAR(64) NOT NULL COMMENT '阿里云地域',
  `endpoint` VARCHAR(128) NOT NULL COMMENT '阿里云图搜访问地址',
  `instance_name` VARCHAR(64) NOT NULL COMMENT '阿里云图搜实例名称',
  `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用，1 启用，0 禁用',
  `add_qps` INT NOT NULL DEFAULT 5 COMMENT '新增或更新图片的 QPS 配置',
  `search_qps` INT NOT NULL DEFAULT 5 COMMENT '查询图片的 QPS 配置',
  `delete_qps` INT NOT NULL DEFAULT 20 COMMENT '删除图片的 QPS 配置',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注说明',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider_region_instance` (`provider`, `region_id`, `instance_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜实例配置表';

-- 图搜图片主表：保存每张业务图片与阿里云索引的当前状态映射
CREATE TABLE IF NOT EXISTS `img_search_image` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `instance_id` BIGINT NOT NULL COMMENT '图搜实例ID',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型，当前一般为 SKU_IMAGE',
  `sku` VARCHAR(64) NOT NULL COMMENT 'SKU 编码',
  `spu` VARCHAR(64) DEFAULT NULL COMMENT 'SPU 编码',
  `image_id` BIGINT NOT NULL COMMENT '业务图片ID',
  `product_id` VARCHAR(128) NOT NULL COMMENT '阿里云 ProductId，建议使用 SKU',
  `pic_name` VARCHAR(128) NOT NULL COMMENT '阿里云 PicName，建议使用图片ID',
  `image_url` VARCHAR(1024) NOT NULL COMMENT '图片访问地址',
  `oss_bucket` VARCHAR(128) DEFAULT NULL COMMENT 'OSS Bucket 名称',
  `oss_object_key` VARCHAR(512) DEFAULT NULL COMMENT 'OSS 对象 Key',
  `image_md5` CHAR(32) DEFAULT NULL COMMENT '图片 MD5 值',
  `mime_type` VARCHAR(128) DEFAULT NULL COMMENT '图片 MIME 类型',
  `file_ext` VARCHAR(16) DEFAULT NULL COMMENT '文件扩展名',
  `file_size` BIGINT DEFAULT NULL COMMENT '文件大小，单位字节',
  `width` INT DEFAULT NULL COMMENT '图片宽度',
  `height` INT DEFAULT NULL COMMENT '图片高度',
  `main_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否主图，1 表示主图',
  `platform_id` BIGINT DEFAULT NULL COMMENT '平台ID',
  `site_id` BIGINT DEFAULT NULL COMMENT '站点ID',
  `category_id` BIGINT DEFAULT NULL COMMENT '类目ID',
  `category_path` VARCHAR(255) DEFAULT NULL COMMENT '类目路径',
  `indexable_flag` TINYINT NOT NULL DEFAULT 1 COMMENT '是否允许建立索引，1 表示允许',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '业务是否删除，1 表示已删除',
  `sync_status` TINYINT NOT NULL DEFAULT 0 COMMENT '同步状态：0待同步 1同步中 2成功 3失败 4已删除',
  `last_task_type` TINYINT DEFAULT NULL COMMENT '最后一次执行的任务类型',
  `version` INT NOT NULL DEFAULT 1 COMMENT '数据版本号，用于避免旧任务覆盖新任务',
  `bucket_no` INT NOT NULL DEFAULT 0 COMMENT '预留分桶编号，便于后续扩容',
  `last_sync_time` DATETIME DEFAULT NULL COMMENT '最后一次同步时间',
  `last_request_id` VARCHAR(64) DEFAULT NULL COMMENT '最后一次调用阿里云接口返回的请求ID',
  `last_error_code` VARCHAR(64) DEFAULT NULL COMMENT '最后一次失败的错误码',
  `last_error_msg` VARCHAR(512) DEFAULT NULL COMMENT '最后一次失败的错误信息',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_image` (`instance_id`, `image_id`),
  UNIQUE KEY `uk_instance_product_pic` (`instance_id`, `product_id`, `pic_name`),
  KEY `idx_sku` (`sku`),
  KEY `idx_sync_status` (`sync_status`),
  KEY `idx_deleted_indexable` (`deleted`, `indexable_flag`),
  KEY `idx_bucket_id` (`bucket_no`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜图片主表';

-- 图搜同步任务表：保存异步同步、删除与重建任务
CREATE TABLE IF NOT EXISTS `img_search_sync_task` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `task_no` VARCHAR(64) NOT NULL COMMENT '任务编号',
  `instance_id` BIGINT NOT NULL COMMENT '图搜实例ID',
  `task_type` TINYINT NOT NULL COMMENT '任务类型：1新增/更新 2删除 3重建 4校验',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `image_pk_id` BIGINT NOT NULL COMMENT '图搜图片主表主键ID',
  `image_id` BIGINT NOT NULL COMMENT '业务图片ID',
  `sku` VARCHAR(64) NOT NULL COMMENT 'SKU 编码',
  `product_id` VARCHAR(128) NOT NULL COMMENT '阿里云 ProductId',
  `pic_name` VARCHAR(128) NOT NULL COMMENT '阿里云 PicName',
  `target_version` INT NOT NULL COMMENT '任务对应的目标版本号',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '任务状态：0待执行 1执行中 2成功 3待重试 4终态失败 5取消',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '当前重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 5 COMMENT '允许的最大重试次数',
  `next_retry_time` DATETIME DEFAULT NULL COMMENT '下次重试时间',
  `trace_id` VARCHAR(64) DEFAULT NULL COMMENT '链路追踪ID',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '阿里云接口请求ID',
  `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
  `error_msg` VARCHAR(512) DEFAULT NULL COMMENT '错误信息',
  `payload_json` JSON DEFAULT NULL COMMENT '任务快照 JSON',
  `start_time` DATETIME DEFAULT NULL COMMENT '开始执行时间',
  `finish_time` DATETIME DEFAULT NULL COMMENT '执行完成时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_status_retry_time` (`status`, `next_retry_time`, `id`),
  KEY `idx_image_version` (`image_pk_id`, `target_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜同步任务表';

-- 图搜重建作业表：记录全量或局部重建的执行情况
CREATE TABLE IF NOT EXISTS `img_search_rebuild_job` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `job_no` VARCHAR(64) NOT NULL COMMENT '重建作业编号',
  `instance_id` BIGINT NOT NULL COMMENT '图搜实例ID',
  `job_type` TINYINT NOT NULL COMMENT '作业类型：1全量重建 2按SKU重建 3按条件重建',
  `scope_desc` VARCHAR(512) DEFAULT NULL COMMENT '作业范围说明',
  `snapshot_max_id` BIGINT DEFAULT NULL COMMENT '本次重建的快照上界ID',
  `total_count` BIGINT NOT NULL DEFAULT 0 COMMENT '本次作业总数据量',
  `success_count` BIGINT NOT NULL DEFAULT 0 COMMENT '本次作业成功数量',
  `fail_count` BIGINT NOT NULL DEFAULT 0 COMMENT '本次作业失败数量',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '作业状态：0待执行 1执行中 2完成 3终止',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注说明',
  `start_time` DATETIME DEFAULT NULL COMMENT '开始执行时间',
  `finish_time` DATETIME DEFAULT NULL COMMENT '完成时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_no` (`job_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜重建作业表';

-- 图搜查询日志表：记录每次以图搜图查询请求
CREATE TABLE IF NOT EXISTS `img_search_query_log` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `query_no` VARCHAR(64) NOT NULL COMMENT '查询编号',
  `instance_id` BIGINT NOT NULL COMMENT '图搜实例ID',
  `biz_scene` VARCHAR(32) NOT NULL COMMENT '业务场景',
  `query_source` TINYINT NOT NULL COMMENT '查询来源：1上传文件 2图片URL 3OSS对象',
  `query_image_md5` CHAR(32) DEFAULT NULL COMMENT '查询图片的 MD5',
  `query_image_url` VARCHAR(1024) DEFAULT NULL COMMENT '查询图片地址',
  `threshold_score` DECIMAL(5,4) DEFAULT NULL COMMENT '相似度阈值',
  `top_k` INT NOT NULL DEFAULT 20 COMMENT '返回结果数量',
  `filter_expr` VARCHAR(1024) DEFAULT NULL COMMENT '传给阿里云的过滤表达式',
  `docs_found` INT DEFAULT NULL COMMENT '查询命中总数',
  `docs_return` INT DEFAULT NULL COMMENT '实际返回数量',
  `search_time_ms` INT DEFAULT NULL COMMENT '查询耗时，单位毫秒',
  `top1_product_id` VARCHAR(128) DEFAULT NULL COMMENT 'Top1 命中的 ProductId',
  `top1_pic_name` VARCHAR(128) DEFAULT NULL COMMENT 'Top1 命中的 PicName',
  `top1_score` DECIMAL(5,4) DEFAULT NULL COMMENT 'Top1 命中的相似度',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '阿里云接口请求ID',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_query_no` (`query_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜查询日志表';

-- 图搜查询结果表：记录一次查询返回的命中结果列表
CREATE TABLE IF NOT EXISTS `img_search_query_result` (
  `id` BIGINT NOT NULL COMMENT '主键ID',
  `query_log_id` BIGINT NOT NULL COMMENT '查询日志主键ID',
  `rank_no` INT NOT NULL COMMENT '命中结果排序',
  `product_id` VARCHAR(128) NOT NULL COMMENT '命中的 ProductId',
  `pic_name` VARCHAR(128) NOT NULL COMMENT '命中的 PicName',
  `sku` VARCHAR(64) DEFAULT NULL COMMENT '命中的 SKU',
  `image_id` BIGINT DEFAULT NULL COMMENT '命中的业务图片ID',
  `score` DECIMAL(5,4) NOT NULL COMMENT '命中结果相似度分值',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图搜查询结果表';
